# Generated by Django 4.2.4 on 2023-09-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_reached', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShipCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_reached', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShipJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_no', models.CharField(max_length=200)),
                ('coal_type', models.CharField(choices=[('Lignite', 'Lignite'), ('Sub-Bituminous', 'Sub-Bituminous'), ('Bituminous', 'Bituminous'), ('Anthracite', 'Anthracite')], max_length=15)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('capacity', models.IntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.buyers')),
            ],
        ),
        migrations.CreateModel(
            name='ShipYard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_reached', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrainJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.CharField(max_length=200)),
                ('coal_type', models.CharField(choices=[('Lignite', 'Lignite'), ('Sub-Bituminous', 'Sub-Bituminous'), ('Bituminous', 'Bituminous'), ('Anthracite', 'Anthracite')], max_length=15)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('capacity', models.IntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.buyers')),
            ],
        ),
        migrations.CreateModel(
            name='TrainStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TruckDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('truck_no', models.CharField(max_length=200, unique=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('aadhar_no', models.CharField(max_length=12, unique=True)),
                ('license_no', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coal_type', models.CharField(choices=[('Lignite', 'Lignite'), ('Sub-Bituminous', 'Sub-Bituminous'), ('Bituminous', 'Bituminous'), ('Anthracite', 'Anthracite')], max_length=15)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('capacity', models.IntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.buyers')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.truckdriver')),
            ],
        ),
        migrations.CreateModel(
            name='TrainJourneyCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_reached', models.BooleanField(default=False)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.traincheckpoint')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.trainjourney')),
            ],
        ),
        migrations.AddField(
            model_name='traincheckpoint',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.trainstation'),
        ),
        migrations.CreateModel(
            name='ShipJourneyCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_reached', models.BooleanField(default=False)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.shipcheckpoint')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.shipjourney')),
            ],
        ),
        migrations.AddField(
            model_name='shipcheckpoint',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.shipyard'),
        ),
        migrations.CreateModel(
            name='JourneyCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_reached', models.BooleanField(default=False)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.checkpoint')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.truckjourney')),
            ],
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.location'),
        ),
    ]
