# Generated by Django 4.2.4 on 2023-09-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodcutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subs', models.CharField(max_length=255)),
                ('target', models.FloatField(default=0)),
                ('fyno', models.FloatField(default=0)),
                ('Achmt', models.FloatField(default=0)),
                ('pastfyno', models.FloatField(default=0)),
                ('growth', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='addProduction',
        ),
    ]
